### ISSUE TITLE
Bug when undocking from cyclops.

### ISSUE THREAD

**Issue by Abrasyve** [pppardo/SNCyclopPitchStrafe#5]
When undocking from the cyclops, the seamoth is suddenly pulled back up and docked while the player is just floating in place in the position of driving the seamoth.

**Comment by pppardo** [comment]
I have not been able to reproduce the problem. Is it produced with any special conditions?

**Comment by Abrasyve** [comment]
Ignore. I had a mod that required SML which I had missed.

**Comment by pppardo** [comment]
Ok, Closed.
